In [1]:
%pylab inline
import seaborn as sns

Populating the interactive namespace from numpy and matplotlib


In [2]:
import numpy as np
import pylab

import nengolib
print nengolib.__file__

c:\users\aaron\ctn\nengolib\nengolib\__init__.pyc


In [3]:
sys = nengolib.Alpha(0.1)

A, B, C, D = sys.ss

C = np.eye(len(A))
D = np.asarray([[0], [0]])

X = nengolib.signal.LinearSystem((A, B, C, D))
print X

(A=[[-20. -100.]
 [  1.   0.]], B=[[ 1.]
 [ 0.]], C=[[ 1.  0.]
 [ 0.  1.]], D=[[0]
 [0]], analog=True)


In [4]:
u = [1., 0, 0, 0]

print sys.filt(u)
print X.filt(u)

for sub in sys:
    print sub.filt(u)

[  4.96679133e-05   1.47685314e-04   2.43747218e-04   3.37882837e-04]
[[  0.00000000e+00   0.00000000e+00]
 [  9.90049834e-04   4.96679133e-07]
 [  9.70347513e-04   1.47685314e-06]
 [  9.50939254e-04   2.43747218e-06]]
[ 0.00099005  0.00097035  0.00095094  0.00093182]
[  4.96679133e-07   1.47685314e-06   2.43747218e-06   3.37882837e-06]


c:\users\aaron\ctn\nengolib\nengolib\signal\system.py:542: UserWarning: Filtering with non-SISO systems is an experimental feature that may not behave as expected.
  "expected.", UserWarning)


In [5]:
assert nengolib.signal.system._is_ccf(A, B, C, D)
assert not X.has_passthrough

In [6]:
hs = nengolib.synapses.HeteroSynapse(X, dt=0.001, elementwise=False)
print hs(0, np.asarray([1, 2]))
print hs(0, np.asarray([1, 2]))
print hs(0, np.asarray([1, 2]))
print hs(0, np.asarray([1, 2]))
print hs(0, np.asarray([1, 2]))

[ 0.  0.  0.  0.]
[  9.90049834e-04   1.98009967e-03   4.96679133e-07   9.93358267e-07]
[  1.96039735e-03   3.92079469e-03   1.97353227e-06   3.94706454e-06]
[  2.91133660e-03   5.82267320e-03   4.41100445e-06   8.82200890e-06]
[  3.84315776e-03   7.68631551e-03   7.78983282e-06   1.55796656e-05]


In [7]:
np.dot(np.asarray([1, 1]), np.ones((2, 4, 4)))

ValueError: shapes (2,) and (2,4,4) not aligned: 2 (dim 0) != 4 (dim 1)

In [ ]:
sys.filt(np.ones((1000, 2, 2, 2))).shape